{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.componentLabels" (dict "root" . "component" "kafka") | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "otel-demo.componentSelectorLabels" (dict "root" . "component" "kafka") | nindent 4 }}
  ports:
  - name: kafka
    port: {{ .Values.kafka.port }}
    targetPort: kafka
    protocol: TCP
  - name: controller
    port: 9093
    targetPort: controller
    protocol: TCP
{{- end }}
