{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jaeger.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.componentLabels" (dict "root" . "component" "jaeger") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "otel-demo.componentSelectorLabels" (dict "root" . "component" "jaeger") | nindent 4 }}
  ports:
  - name: ui
    port: {{ .Values.jaeger.ports.ui }}
    targetPort: ui
    protocol: TCP
  - name: otlp-grpc
    port: {{ .Values.jaeger.ports.collector }}
    targetPort: otlp-grpc
    protocol: TCP
{{- end }}
