{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.otelCollector.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.componentLabels" (dict "root" . "component" "otel-collector") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "otel-demo.componentSelectorLabels" (dict "root" . "component" "otel-collector") | nindent 4 }}
  ports:
  - name: otlp-grpc
    port: {{ .Values.otelCollector.ports.grpc }}
    targetPort: otlp-grpc
    protocol: TCP
  - name: otlp-http
    port: {{ .Values.otelCollector.ports.http }}
    targetPort: otlp-http
    protocol: TCP
  - name: prometheus
    port: 8889
    targetPort: prometheus
    protocol: TCP
{{- end }}
