{{- if .Values.cart.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cart.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.componentLabels" (dict "root" . "component" "cart") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "otel-demo.componentSelectorLabels" (dict "root" . "component" "cart") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel-demo.componentLabels" (dict "root" . "component" "cart") | nindent 8 }}
    spec:
      {{- include "otel-demo.imagePullSecrets" . | nindent 6 }}
      containers:
      - name: cart
        image: "{{ .Values.cart.image.repository }}:{{ .Values.cart.image.tag }}"
        imagePullPolicy: {{ .Values.demo.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.cart.port }}
          name: grpc
        env:
        {{- include "otel-demo.otelEnv" . | nindent 8 }}
        {{- include "otel-demo.flagdEnv" . | nindent 8 }}
        {{- with .Values.cart.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.cart.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
