{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "otel-demo.componentSelectorLabels" (dict "root" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel-demo.componentLabels" (dict "root" . "component" "frontend") | nindent 8 }}
    spec:
      {{- include "otel-demo.imagePullSecrets" . | nindent 6 }}
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.demo.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
          name: http
        env:
        {{- include "otel-demo.otelEnv" . | nindent 8 }}
        {{- include "otel-demo.flagdEnv" . | nindent 8 }}
        - name: ENV_PLATFORM
          value: "kubernetes"
        - name: OTEL_COLLECTOR_HOST
          value: {{ .Values.otelCollector.name }}
        - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://localhost:8080/otlp-http/v1/traces"
        {{- with .Values.frontend.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
