{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "otel-demo.componentSelectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.frontend.port }}
    targetPort: http
    protocol: TCP
{{- end }}