name: Helm Chart Release

on:
  push:
    tags:
      - 'v*'

env:
  HELM_VERSION: '3.14.0'

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update Chart.yaml with release version
        run: |
          sed -i "s/^version:.*/version: ${{ steps.version.outputs.version }}/" helm-chart/otel-demo/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: ${{ steps.version.outputs.version }}/" helm-chart/otel-demo/Chart.yaml

      - name: Lint Helm chart
        run: |
          helm lint helm-chart/otel-demo

      - name: Package Helm chart
        run: |
          helm package helm-chart/otel-demo --destination ./packages

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: OpenTelemetry Demo Base14 Fork ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false
          body: |
            ## Helm Chart Release ${{ steps.version.outputs.tag }}

            ### Changes
            - OpenTelemetry Demo Base14 Fork
            - Scout observability integration
            - Multi-language service support

            ### Installation
            ```bash
            # Add the chart
            helm repo add base14-otel-demo https://github.com/base-14/otel-demo/releases/download/${{ steps.version.outputs.tag }}/

            # Install the chart
            helm install otel-demo base14-otel-demo/otel-demo --version ${{ steps.version.outputs.version }}
            ```

            ### With Scout Integration
            ```bash
            # Create values file for Scout
            cat > values-scout.yaml << EOF
            scout:
              enabled: true
              endpoint: "https://your-scout-endpoint"
              appName: "your-app-name"
              apiKey: "your-api-key"

            telemetry:
              enabled: false  # Disable built-in telemetry when using Scout
            EOF

            # Install with Scout
            helm install otel-demo base14-otel-demo/otel-demo -f values-scout.yaml --version ${{ steps.version.outputs.version }}
            ```

      - name: Upload Helm Chart to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./packages/otel-demo-${{ steps.version.outputs.version }}.tgz
          asset_name: otel-demo-${{ steps.version.outputs.version }}.tgz
          asset_content_type: application/gzip

      - name: Generate Helm repo index
        run: |
          mkdir -p helm-repo
          cp ./packages/otel-demo-${{ steps.version.outputs.version }}.tgz helm-repo/
          helm repo index helm-repo --url https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.tag }}/

      - name: Upload Helm repo index
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./helm-repo/index.yaml
          asset_name: index.yaml
          asset_content_type: application/yaml

      - name: Summary
        run: |
          echo "## 🚀 Helm Chart Released Successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Chart:** otel-demo-${{ steps.version.outputs.version }}.tgz" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation Commands:" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "# Download the chart" >> $GITHUB_STEP_SUMMARY
          echo "wget https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.tag }}/otel-demo-${{ steps.version.outputs.version }}.tgz" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Install the chart" >> $GITHUB_STEP_SUMMARY
          echo "helm install otel-demo ./otel-demo-${{ steps.version.outputs.version }}.tgz" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
